# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_usercategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
