# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_amount_method',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_txn_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_date',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_method',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='down_payment_txn_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=datetime.datetime(2016, 7, 7, 11, 50, 55, 28542)),
        ),
    ]
