# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_auto_20160707_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=datetime.datetime(2016, 7, 7, 12, 7, 26, 253070)),
        ),
    ]
