# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0004_auto_20160708_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
