# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0005_auto_20160717_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_converted',
            field=models.BooleanField(default=False),
        ),
    ]
