# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20160623_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
