# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_auto_20160706_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMI_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now)),
                ('emi_schedule_date', models.DateField(null=True)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('paid_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='emi',
            old_name='paid',
            new_name='paid_status',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='emi',
            name='emi_schedule_date',
        ),
        migrations.RemoveField(
            model_name='saletransaction',
            name='emi',
        ),
        migrations.AddField(
            model_name='emi',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='emi',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='emi',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='emi',
            name='total_intrest',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='emi_transactions',
            name='emi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_data', to='accounts_api.EMI'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='emi_txn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sales_transaction_emi', to='accounts_api.EMI_transactions'),
            preserve_default=False,
        ),
    ]
