# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_auto_20160706_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='duration',
            field=models.IntegerField(default=False),
        ),
    ]
