# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0005_auto_20160706_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_sale', to='accounts_api.Sale'),
        ),
    ]
