# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254)),
                ('middle_name', models.CharField(blank=True, max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=254)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=254)),
                ('alternet_mobile', models.CharField(blank=True, max_length=254)),
                ('address1', models.CharField(blank=True, max_length=254)),
                ('address2', models.CharField(blank=True, max_length=254)),
                ('pin_code', models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
