# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='agriculture_status',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='marriage_anniversary',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_address',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_age',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_alternet_mobile',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_dob',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_mobile',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_occupation',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nominee_photo',
            field=models.ImageField(null=True, upload_to='nominee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(null=True, upload_to='customers'),
        ),
        migrations.AddField(
            model_name='customer',
            name='purpose_of_buying',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='relation',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
