# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0002_auto_20160626_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nominee_address',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purpose_of_buying',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
