# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_auto_20160706_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='emi_day',
            field=models.IntegerField(default=False),
        ),
    ]
