# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_emi_emi_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='source',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transaction_sale', to='accounts_api.Sale'),
        ),
    ]
