# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0005_auto_20160713_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='accounts_api.Sale'),
        ),
    ]
