# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import plots.lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_api', '0004_auto_20160703_0530'),
        ('projects_api', '0013_project_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=254)),
                ('updated_at', plots.lib.utils.AutoDateTimeField(default=datetime.datetime(2016, 7, 6, 15, 16, 4, 628573))),
                ('booking_amount', models.CharField(blank=True, max_length=254)),
                ('is_booking_cancled', models.CharField(blank=True, max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer_api.Customer')),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects_api.Plots')),
            ],
        ),
    ]
