# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plots.lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects_api', '0003_auto_20160624_1257'),
        ('customer_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now)),
                ('booking_amount', models.CharField(blank=True, max_length=254)),
                ('is_booking_cancled', models.CharField(blank=True, max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer_api.Customer')),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='projects_api.Plots')),
            ],
        ),
    ]
