# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=b'06/07/2016'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=b'06/07/2016'),
        ),
    ]
