# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_auto_20160706_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.CharField(default=b'06/07/2016', max_length=254),
        ),
    ]
