# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0003_auto_20160707_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
