# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0011_auto_20160626_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='rate_per_sqft',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rate_per_sqft',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
