# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0003_auto_20160626_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='alternet_mobile',
            new_name='alternate_mobile',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nominee_alternet_mobile',
            new_name='nominee_alternate_mobile',
        ),
    ]
