# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plots.lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback_api.Feedback')),
            ],
        ),
    ]
