# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0013_project_village'),
        ('feedback_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_feedback', to='projects_api.Project'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_feedback', to='feedback_api.Feedback'),
        ),
    ]
