# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0002_auto_20160624_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plots',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
