# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 10:07
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import plots.lib.utils


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0004_auto_20160625_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=plots.lib.utils.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
