# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0007_auto_20160625_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
