# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0009_auto_20160625_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='gat_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='plots',
            name='survey_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='survey_no',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='taluka',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
