# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0010_auto_20160626_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
