# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_api', '0012_auto_20160626_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='village',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
